### ISSUE TITLE
Pretrained model & bounce detection

### ISSUE THREAD

**Issue by pltrdy** [SamuReyes/TrackNetV2-padel#2]
Hi,

Thanks for your interesting work.

I supposed you trained the model yourself, so:
1) could you provide the weight?
2) what camera angle / data source did you used? 
3) could you share performance evaluation?

And as a final question, did you investigate bounce detection i.e. detecting when ball bounce off the ground/side wall/back wall/fence or is hit by a player?

Thanks

**Comment by SamuReyes** [comment]
Hello!

Thank you for reaching out. Here are the answers to your questions:

1. I've attached the best model I've trained for your use. ([link to the model](https://upm365-my.sharepoint.com/:u:/g/personal/samuel_reyes_sanz_alumnos_upm_es/EZVpfL9ltOpGtDxhtEnEQ2YB0e4ojR00ga8jd84JrwpXBA?e=yuzxP3))
2. The camera angle for all World Padel Tour matches is consistent, as evidenced by examples available on YouTube.
3. You can find the model's evaluation in the paper uploaded to the repository, with key details on page 38 (note: the paper is in Spanish).
4. Although I explored this topic, I haven't applied it practically. For enhanced model performance, I recommend exploring vision transformers. This involves performing a pixel-level classification to determine the presence of a ball and whether it's bouncing or being hit by a player.

Please feel free to contact me if you have any questions.

**Comment by pltrdy** [comment]
Hi,

First thank you very much for answering quickly and with details! I found and translated your paper, lots of useful information thanks!

**Comment by pltrdy** [comment]
@SamuReyes to be sure that I get it right, you would suggest to do the whole ball tracking using a Vision Transformer instead of TrackNet? Do you have resources about that? Or are you specifically talking about the bounce detection problem? 

I'm planning to train ball tracking system soon on amateur level videos

**Comment by SamuReyes** [comment]
If you have time to invest in improving the system, I would suggest implementing a transformer-based model. When I was researching this topic, I found [this paper](https://www.mdpi.com/1424-8220/23/3/1726) about that. However, if you don't have much time, you could train my network and still obtain good results.

**Comment by pltrdy** [comment]
Hi, I'm curious about the topic but I do have time so thank you very much for this resource.

The model without finetuning struggles when the ball is if front on a player or the racket or depending on the court background. This make sense since your data (WPT) is way cleaner and with different angles that my amateur level mid-quality video at glass level

**Comment by SamuReyes** [comment]
You're using my model to initialize the weights, aren't you?

**Comment by pltrdy** [comment]
I fact I used the weights as is. Not fine tuning so I could not expect it
to be perfectly robust to other experimental setup.

Sad that I found no implementation of the paper you mentioned. I might just
fine-tune your model since it seems to not require too much data (you
mention a total of 10 mins that I could preannotate with your model)

**Comment by pltrdy** [comment]
Also, do you know you does TrackNet compares to vision transformers in terms of computation speed/cost?

Sorry to bother you with this much question, I'm curious about the field that is new to me, coming from NLP. Are you interested on spending some extra-time on this topic? We could discuss on private messaging/mail
